"""Type stubs for msgq.ipc_pyx Cython module."""

from typing import Optional
from typing_extensions import TypeAlias

# Cython with c_string_encoding=ascii accepts both str and bytes for string params
_String: TypeAlias = str | bytes

class IpcError(Exception):
    def __init__(self, endpoint: Optional[_String] = None) -> None: ...

class MultiplePublishersError(IpcError): ...

def toggle_fake_events(enabled: bool) -> None: ...
def set_fake_prefix(prefix: _String) -> None: ...
def get_fake_prefix() -> bytes: ...
def delete_fake_prefix() -> None: ...
def wait_for_one_event(events: list[Event], timeout: int = -1) -> int: ...

class Event:
    @property
    def fd(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    def set(self) -> None: ...
    def clear(self) -> int: ...
    def wait(self, timeout: int = -1) -> None: ...
    def peek(self) -> bool: ...

class SocketEventHandle:
    def __init__(self, endpoint: _String, identifier: _String, override: bool) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def recv_called_event(self) -> Event: ...
    @property
    def recv_ready_event(self) -> Event: ...

class Context:
    def term(self) -> None: ...

class Poller:
    def registerSocket(self, socket: SubSocket) -> None: ...
    def poll(self, timeout: int) -> list[SubSocket]: ...

class SubSocket:
    def connect(
        self,
        context: Context,
        endpoint: _String,
        address: _String = b"127.0.0.1",
        conflate: bool = False,
        segment_size: int = 0,
    ) -> None: ...
    def setTimeout(self, timeout: int) -> None: ...
    def receive(self, non_blocking: bool = False) -> Optional[bytes]: ...

class PubSocket:
    def connect(self, context: Context, endpoint: _String, segment_size: int = 0) -> None: ...
    def send(self, data: bytes) -> None: ...
    def all_readers_updated(self) -> bool: ...
