name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: ./test.sh
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'ubuntu-24.04-arm']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - run: ./test.sh
        timeout-minutes: 1
